name: Desktop and Web

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build-number:
    uses: ./.github/workflows/build-number.yml

  Build-Desktop:
    runs-on: ubuntu-latest
    needs: build-number
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'zulu'

      - name: Setup gradle
        uses: gradle/setup-gradle-action@v3
        with:
          gradle-home-cache-cleanup: true
          cache-write-only: ${{ github.event_name == 'push' }}
          cache-encryption-key: ${{ secrets.GRADLE_ENCRYPTION_KEY }}

      - name: Build with Gradle
        run: ./gradlew composeApp:desktopJar

  Build-Web:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'zulu'

      - name: Setup gradle
        uses: gradle/setup-gradle-action@v3
        with:
          gradle-home-cache-cleanup: true
          cache-write-only: ${{ github.event_name == 'push' }}
          cache-encryption-key: ${{ secrets.GRADLE_ENCRYPTION_KEY }}

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '10.x'

      - name: Build with Gradle
        run: ./gradlew composeApp:jsJar