name: Desktop and Web CI

on:
  push:
    branches:
    - main
  pull_request:
    branches:
      - main
      
jobs:
  Build-Desktop:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew desktop:assemble

  Build-Web:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '10.x'

      - name: Build with Gradle
        run: ./gradlew jsApp:assemble