name: iOS CI

on: 
  push: 
    branches: 
      - main
  pull_request: 
    branches: 
      - main

jobs: 
  build: 
    runs-on: macos-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - shell: bash
        run: ./gradlew generateDummyFramework

      - name: Set up cocoapods
        uses: maxim-lobanov/setup-cocoapods@v1
        with: 
          version: latest

      - name: Install cocoapods
        shell: bash
        run: ./gradlew podInstall

      - name: Build with Gradle
        run: ./gradlew iosSimulatorArm64Binaries
